## numPy exercise

In [2]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)


arr = np.array(42)

print(arr)

[1 2 3 4 5]
42


#### Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D arrays
#### An array that has 2-D arrays (matrices) as its elements is called 3-D array.
##### These are often used to represent a 3rd order tensor.

In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Check Number of Dimensions?
#### NumPy Arrays provides the **ndim** attribute that returns an _integer_ that tells us how many dimensions the array have.

In [7]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher Dimensional Arrays
#### An array can have any number of dimensions.
#### When the array is created, you can define the number of dimensions by using the **ndmin** argument.

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [21]:
# x,y,z = "Mery","Rose","Maro"
# print(x)
# print(z)
# print(y)

# fruits = ['apple', 'banana', 'cherry']
# a, b, c = fruits
# print(a)

# x = "Hello World"
# print(type(x))

# x = ["apple", "banana", "cherry"]
# print(type(x))

# x=5
# x=float(x)
# print(x)

# x = 5.5
# x = int(x)
# print (x)

# x = 5
# x = complex(x)
# print(x)


# x = 'Welcome'
# print(x[3])

txt = 'Hello World'
print(txt[0])

H
